### ISSUE TITLE
Create check type: address-size

### ISSUE THREAD

**Issue by chasinglogic** [chasinglogic/redalert#12]

**Comment by ehershey** [comment]
notes - this is a ulimit check

**Comment by ehershey** [comment]
More notes - 
- this will probably be a ulimit type instead of an address-size type
- and will therefore require additional logic in [the conversion script](https://github.com/chasinglogic/redalert/blob/2f99d197cae6b2949de46cb94814f2bd175b30ee/scripts/convert_greenbay_yaml.py)
